version: "3"
services:
  # doitwrite:
  #   build:
  #     context: .
  db:
    image: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doitwrite
