name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}  # Pass the GitHub Secret

          # Other .npmrc values:  Uncomment if needed.  Define the secrets first.
          # NPM_REGISTRY=${{ secrets.NPM_REGISTRY }}
          # NPM_EMAIL=${{ secrets.NPM_EMAIL }}
